# Generated by Django 5.2.6 on 2026-01-15 14:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_cat', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=25, unique=True)),
                ('color', models.CharField(max_length=7, unique=True)),
                ('tipo', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_cont', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=25, unique=True)),
                ('orden_pauta', models.CharField(blank=True, max_length=255, null=True)),
                ('notas', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='catalogo.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_prod', models.CharField(max_length=10, unique=True)),
                ('titulo', models.CharField(max_length=50)),
                ('duracion_total', models.DurationField(default=datetime.timedelta(0))),
                ('origen', models.CharField(help_text='Live-1, Live-2, Servidor', max_length=20)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='catalogo.contenido')),
            ],
            options={
                'verbose_name': 'Producción',
                'verbose_name_plural': 'Producciones',
            },
        ),
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_seg', models.CharField(max_length=10)),
                ('duracion', models.DurationField(default=datetime.timedelta(0))),
                ('tc_in', models.DurationField(default=datetime.timedelta(0))),
                ('tc_out', models.DurationField(default=datetime.timedelta(0))),
                ('notas', models.CharField(blank=True, max_length=255, null=True)),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentos', to='catalogo.produccion')),
            ],
            options={
                'verbose_name': 'Segmento',
                'verbose_name_plural': 'Segmentos',
            },
        ),
    ]
