# Generated by Django 5.2.6 on 2025-11-11 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cat', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('color', models.CharField(max_length=7, unique=True)),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cont', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='catalogo.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prod', models.CharField(max_length=10, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('media_id', models.CharField(help_text='Nombre del archivo de video/audio', max_length=255)),
                ('duracion', models.DurationField()),
                ('origen', models.CharField(max_length=100)),
                ('logo', models.CharField(blank=True, max_length=100, null=True)),
                ('expiracion', models.DateField(blank=True, null=True)),
                ('episodio', models.IntegerField(blank=True, null=True)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='catalogo.contenido')),
            ],
            options={
                'verbose_name': 'Producción',
                'verbose_name_plural': 'Producciones',
            },
        ),
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentos', to='catalogo.produccion')),
            ],
            options={
                'verbose_name': 'Segmento',
                'verbose_name_plural': 'Segmentos',
            },
        ),
    ]
