# Generated by Django 4.2.15 on 2026-01-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmento',
            name='id_media',
            field=models.CharField(default='PENDIENTE', max_length=255),
        ),
    ]
