# Generated by Django 4.2.15 on 2026-01-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_segmento_id_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='id_prod',
        ),
        migrations.RemoveField(
            model_name='segmento',
            name='id_seg',
        ),
    ]
