# Generated by Django 4.2.15 on 2026-01-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_remove_produccion_id_prod_remove_segmento_id_seg'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmento',
            name='id_seg',
            field=models.CharField(default='PENDIENTE', max_length=100),
        ),
    ]
