# Generated by Django 4.2.15 on 2026-01-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_segmento_id_seg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segmento',
            old_name='id_seg',
            new_name='titulo',
        ),
    ]
