# Generated by Django 4.2.15 on 2026-01-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_rename_id_seg_segmento_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='duracion_total',
        ),
        migrations.RemoveField(
            model_name='segmento',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='segmento',
            name='tc_in',
        ),
        migrations.RemoveField(
            model_name='segmento',
            name='tc_out',
        ),
    ]
