# Generated by Django 4.2.15 on 2026-01-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_remove_produccion_duracion_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='duracion_total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='segmento',
            name='duracion',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='segmento',
            name='tc_in',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='segmento',
            name='tc_out',
            field=models.BigIntegerField(default=0),
        ),
    ]
