# Generated by Django 4.2.15 on 2026-03-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_produccion_duracion_total_segmento_duracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
