# Generated by Django 4.2.15 on 2026-03-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_produccion_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido',
            name='orden_pauta',
        ),
        migrations.AddField(
            model_name='produccion',
            name='orden_pauta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
