# Generated by Django 5.2.6 on 2025-09-23 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporteria', '0002_auto_20250923_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'broadcast_systems',
            },
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('sistemas', models.JSONField()),
            ],
            options={
                'db_table': 'reportes',
            },
        ),
        migrations.CreateModel(
            name='AsRunLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='log_files', to='reporteria.broadcastsystem')),
            ],
            options={
                'db_table': 'asrun_log_files',
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('contents', models.TextField(blank=True, null=True)),
                ('clip_name', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('log_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='reporteria.asrunlogfile')),
            ],
            options={
                'db_table': 'log_entries',
            },
        ),
    ]
