# Generated by Django 4.2.15 on 2026-01-31 13:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Categoría')),
                ('color', models.CharField(default='#3b82f6', help_text='Color en formato HEX (ej: #FF5733)', max_length=7)),
            ],
            options={
                'verbose_name': 'Categoría de Bloque',
                'verbose_name_plural': 'Categorías de Bloques',
            },
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Bloque')),
                ('duracion_teorica', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Duración Teórica (Frames)')),
                ('duracion_real', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Duración Real (Frames)')),
                ('notas', models.TextField(blank=True, help_text='Comentarios para el operador', null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bloques', to='programacion.bloquecategoria')),
            ],
            options={
                'verbose_name': 'Bloque',
                'verbose_name_plural': 'Bloques',
                'ordering': ['nombre'],
            },
        ),
    ]
