# Generated by Django 4.2.15 on 2026-02-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Plantilla')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('eventos', models.JSONField(help_text='Array de objetos JSON con la data de los bloques', verbose_name='Contenido de la Plantilla')),
            ],
            options={
                'verbose_name': 'Plantilla',
                'verbose_name_plural': 'Plantillas',
                'ordering': ['-fecha_de_creacion'],
            },
        ),
    ]
