# Generated by Django 4.2.15 on 2026-02-05 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0002_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('background_color', models.CharField(default='#001EB4', max_length=7)),
                ('extended_props', models.JSONField(blank=True, default=dict)),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='programacion.calendario')),
            ],
        ),
    ]
