# Generated by Django 4.2.15 on 2026-03-10 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_produccion_duracion_total_segmento_duracion_and_more'),
        ('programacion', '0003_calendario_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('start_time_ff', models.BigIntegerField(default=0)),
                ('custom_id', models.CharField(blank=True, max_length=100, null=True)),
                ('scotys', models.CharField(default='Off', max_length=10)),
                ('tape', models.CharField(blank=True, max_length=255, null=True)),
                ('op_id', models.CharField(blank=True, max_length=255, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='programacion.evento')),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usado_en_items', to='catalogo.segmento')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
